package com.logbookmanager.domain.model.person;

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import com.logbookmanager.domain.support.EntitySupport;

/**
 * PersonEntry generated by hbm2java
 */
public class PersonEntry extends EntitySupport<PersonEntry, Long> implements
		java.io.Serializable {
	private static final long serialVersionUID = 912839123L;

	// Fields

	// which personlogbook this entry belongs to, we can navigate to the person
	// from their logbook
	private PersonLogbook personLogbook;

	// hold the person to prevent the need to load the person logbook just to
	// retrieve the user this entry belongs to
	private Person person;

	private Integer entryNumber;

	private Set<EntryAttribute> entryAttributes = new HashSet<EntryAttribute>();

	// Constructors

	/** default constructor required by Hibernate */
	PersonEntry() {
	}

	/**
	 * 
	 */
	public PersonLogbook getPersonLogbook() {
		return this.personLogbook;
	}

	public void setPersonLogbook(PersonLogbook personLogbook) {
		this.personLogbook = personLogbook;
	}

	/**
	 * 
	 */
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	/**
	 * 
	 */
	public Integer getEntryNumber() {
		return this.entryNumber;
	}

	public void setEntryNumber(Integer entryNumber) {
		this.entryNumber = entryNumber;
	}

	/**
	 * 
	 */
	public Set<EntryAttribute> getEntryAttributes() {
		return this.entryAttributes;
	}

	public void setEntryAttributes(Set<EntryAttribute> entryAttributes) {
		this.entryAttributes = entryAttributes;
	}

	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof PersonEntry)) {
			return false;
		}
		PersonEntry rhs = (PersonEntry) object;
		return new EqualsBuilder().append(this.entryNumber, rhs.entryNumber)
				.append(this.id, rhs.id).isEquals();
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder(-886008693, -818375109)
				.append(this.entryNumber).append(this.id).toHashCode();
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return new ToStringBuilder(this).append("id", this.id)
				.append("entryNumber", this.entryNumber).toString();
	}

}