package com.logbookmanager.domain.model.person;

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import com.logbookmanager.domain.model.logbook.Logbook;
import com.logbookmanager.domain.support.EntitySupport;

/**
 * PersonLogbook generated by hbm2java
 */
public class PersonLogbook extends EntitySupport<PersonLogbook, Long> implements
		java.io.Serializable {
	private static final long serialVersionUID = 912839123L;

	// Fields

	private Logbook logbook;

	private Person person;

	private String name;

	private Set<PersonLogbookDetail> logbookDetails = new HashSet<PersonLogbookDetail>();

	private Set<PersonEntry> userEntries = new HashSet<PersonEntry>();

	// Constructors

	/** default constructor required by Hibernate */
	PersonLogbook() {
	}

	/**
	 * 
	 */
	public Logbook getLogbook() {
		return this.logbook;
	}

	public void setLogbook(Logbook logbook) {
		this.logbook = logbook;
	}

	/**
	 * 
	 */
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	/**
	 * 
	 */
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<PersonLogbookDetail> getLogbookDetails() {
		return logbookDetails;
	}

	public void setLogbookDetails(Set<PersonLogbookDetail> logbookDetails) {
		this.logbookDetails = logbookDetails;
	}

	public Set<PersonEntry> getUserEntries() {
		return userEntries;
	}

	public void setUserEntries(Set<PersonEntry> userEntries) {
		this.userEntries = userEntries;
	}

	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof PersonLogbook)) {
			return false;
		}
		PersonLogbook rhs = (PersonLogbook) object;
		return new EqualsBuilder()
				.append(this.logbook.getId(), rhs.logbook.getId())
				.append(this.id, rhs.id)
				.append(this.person.getId(), rhs.person.getId())
				.append(this.name, rhs.name).append(this.version, rhs.version)
				.isEquals();
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder(-94869041, 2116460323)
				.append((logbook==null)?5:this.logbook.getId()).append(this.id)
				.append((person==null)?5:this.person.getId()).append(this.name)
				.append(this.version).toHashCode();
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return new ToStringBuilder(this).append("name", this.name)
				.append("version", this.version)
				.append("personId", (person==null)?"[null]":this.person.getId())
				.append("logbookId", (logbook==null)?"[null]":this.logbook.getId())
				.append("id", this.id).toString();
	}

}