package com.logbookmanager.domain.model.person;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import com.logbookmanager.domain.model.organisation.Qualification;
import com.logbookmanager.domain.support.EntitySupport;

/**
 * PersonQualification generated by hbm2java
 */
public class PersonQualification extends
		EntitySupport<PersonQualification, Long> implements
		java.io.Serializable {
	private static final long serialVersionUID = 912839123L;

	// Fields
	private Person person;

	private Qualification qualification;

	// Constructors

	/** default constructor required by Hibernate */
	PersonQualification() {
	}

	/**
	 * 
	 */
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	/**
	 * 
	 */
	public Qualification getQualification() {
		return this.qualification;
	}

	public void setQualification(Qualification qualification) {
		this.qualification = qualification;
	}

	/**
	 * @see java.lang.Object#equals(Object)
	 */
	@Override
	public boolean equals(Object object) {
		if (!(object instanceof PersonQualification)) {
			return false;
		}
		PersonQualification rhs = (PersonQualification) object;
		return new EqualsBuilder().append(this.person, rhs.person)
				.append(this.qualification, rhs.qualification)
				.append(this.id, rhs.id).append(this.version, rhs.version)
				.isEquals();
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder(-703046579, 449405865).append(this.person)
				.append(this.qualification).append(this.id)
				.append(this.version).toHashCode();
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return new ToStringBuilder(this).append("id", this.id)
				.append("version", this.version).append("person", this.person)
				.append("qualification", this.qualification).toString();
	}

}