SET SCHEMA = APP;
--DROP TABLE ApplicationUser; 
--DROP TABLE sec_user_role;
--DROP TABLE sec_role;
--DROP TABLE sec_user;
--DROP TABLE persistent_logins;


CREATE TABLE persistent_logins (username VARCHAR(64) NOT NULL,
                                    series VARCHAR(64) PRIMARY KEY,
                                    token VARCHAR(64) NOT NULL,
                                    last_used TIMESTAMP NOT NULL)

CREATE TABLE ApplicationUser (
	userId int NOT NULL,
	forename VARCHAR(50) NOT NULL,
	surname VARCHAR(50) NOT NULL, 
	CONSTRAINT USERID_PK PRIMARY KEY (UserId)  
);

CREATE TABLE SEC_USER (
	ID BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	username VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	active BOOLEAN DEFAULT TRUE,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	version BIGINT DEFAULT NULL,
	email VARCHAR(50) NOT NULL,
	postal_code VARCHAR(7) NOT NULL,
	city VARCHAR(50) NOT NULL,
	CONSTRAINT SEC_USER_ID_PK PRIMARY KEY (id)
);

CREATE TABLE SEC_ROLE (
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	name VARCHAR(50) NOT NULL,
	version INTEGER DEFAULT 0,
	CONSTRAINT SEC_ROLE_ID_PK PRIMARY KEY (id)
);

CREATE TABLE SEC_USER_ROLE (
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	user_id BIGINT NOT NULL,
	role_id BIGINT NOT NULL,
	CONSTRAINT SEC_USER_ROLE_ID_PK PRIMARY KEY (id)
);

CREATE TABLE PERSISTENT_LOGIN (
  username VARCHAR(64) NOT NULL,
  series VARCHAR(64) PRIMARY KEY,
  token VARCHAR(64) NOT NULL,
  last_used TIMESTAMP NOT NULL);

SELECT username,password,active FROM sec_user WHERE username = 'peterneil';

-- INSERT Roles
INSERT INTO sec_role (version, name) VALUES(1,'logbookuser'); -- a user of logbooks
INSERT INTO sec_role (version, name) VALUES(1,'admin'); -- administers logbooks
INSERT INTO sec_role (version, name) VALUES(1,'guestuser'); -- guest to the web site who has not provided any personal information
INSERT INTO sec_role (version, name) VALUES(1,'registereduser'); -- a person without a logbook, but they have registered

--INSERT SecUsers
INSERT INTO sec_user (active, username, first_name, last_name, version, password, email, postal_code, city) VALUES(1, 'peterneil', 'Peter', 'Neil', 1, 'password', 'peterneil_world@yahoo.co.uk', 'WS149ZY', 'Lichfield');
INSERT INTO sec_user (active, username, first_name, last_name, version, password, email, postal_code, city)  VALUES(1, 'peterneil-admin', 'Peter', 'Neil', 1, 'password', 'saffadiver@yahoo.co.uk', 'WS149ZY', 'Lichfield');
INSERT INTO sec_user (active, username, first_name, last_name, version, password, email, postal_code, city)  VALUES(1, 'todelete', 'Peter', 'Neil', 1, 'password', 'neil.peter@yahoo.co.uk', 'WS149ZY', 'Lichfield');
INSERT INTO sec_user (active, username, first_name, last_name, version, password, email, postal_code, city) VALUES(1, 'peterneil3', 'Peter', 'Neil', 1, 'password', 'pedroneil@gmail.com', 'WS149ZY', 'Lichfield');
INSERT INTO sec_user (active, username, first_name, last_name, version, password, email, postal_code, city) VALUES(1, 'guestuser', 'Logbook', 'Guest', 1, 'password', 'logbookguest@yahoo.co.uk', 'WS149ZY', 'Lichfield');

INSERT INTO sec_user_role (
	SELECT 1 as id, su.id as user_id, sr.id as role_id FROM sec_user su, sec_role sr WHERE su.username='peterneil' and sr.name = 'logbookuser'
);
INSERT INTO sec_user_role (
	SELECT 2 as id, su.id as user_id, sr.id as role_id FROM sec_user su, sec_role sr WHERE su.username='peterneil-admin' and sr.name = 'admin'
);
INSERT INTO sec_user_role (
	SELECT 3 as id, su.id as user_id, sr.id as role_id FROM sec_user su, sec_role sr WHERE su.username='todelete' and sr.name = 'registereduser'
);
INSERT INTO sec_user_role (
	SELECT 4 as id, su.id as user_id, sr.id as role_id FROM sec_user su, sec_role sr WHERE su.username='guestuser' and sr.name = 'guestuser'
);

select max(id) from sec_user_role as max_value;
ALTER TABLE sec_user_role ALTER id RESTART WITH max_value + 1;
select max_value;

SELECT * FROM sec_user;
SELECT * FROM sec_role;
SELECT * FROM sec_user_role;
SELECT * FROM sec_user WHERE username = 'peterneil';

SELECT
	su.username, sr.name
FROM
	APP.sec_user_role sur,
	APP.sec_user su,
	APP.sec_role sr
WHERE
	su.ID = sur.user_ID and
	sur.role_ID = sr.ID
AND
	su.username = 'peterneil1'