package com.logbookmanager.domain.model.logbook;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import com.logbookmanager.domain.model.organisation.Qualification;
import com.logbookmanager.domain.support.EntitySupport;

/**
 * LogbookUserQualification generated by hbm2java
 */
public class LogbookUserQualification extends
		EntitySupport<LogbookUserQualification, Long> implements
		java.io.Serializable {
	private static final long serialVersionUID = 912839123L;

	// Fields
	private LogbookUser logbookUser;

	private Qualification qualification;

	// Constructors

	/** default constructor required by Hibernate */
	LogbookUserQualification() {
	}

	/**
	 * 
	 */
	public LogbookUser getLogbookUser() {
		return this.logbookUser;
	}

	public void setLogbookUser(LogbookUser logbookUser) {
		this.logbookUser = logbookUser;
	}

	/**
	 * 
	 */
	public Qualification getQualification() {
		return this.qualification;
	}

	public void setQualification(Qualification qualification) {
		this.qualification = qualification;
	}

	/**
	 * @see java.lang.Object#equals(Object)
	 */
	@Override
	public boolean equals(Object object) {
		if (!(object instanceof LogbookUserQualification)) {
			return false;
		}
		LogbookUserQualification rhs = (LogbookUserQualification) object;
		return new EqualsBuilder().append(this.logbookUser, rhs.logbookUser)
				.append(this.qualification, rhs.qualification)
				.append(this.id, rhs.id).append(this.version, rhs.version)
				.isEquals();
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder(-703046579, 449405865).append(this.logbookUser)
				.append(this.qualification).append(this.id)
				.append(this.version).toHashCode();
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return new ToStringBuilder(this).append("id", this.id)
				.append("version", this.version).append("logbookUser", this.logbookUser)
				.append("qualification", this.qualification).toString();
	}

}