--<ScriptOptions statementTerminator=";"/>

ALTER TABLE APPLICATIONUSER DROP CONSTRAINT USERID_PK;

DROP INDEX SQL130119003746730;

DROP TABLE APPLICATIONUSER;

CREATE TABLE APPLICATIONUSER (
		USERID INTEGER NOT NULL,
		FORENAME VARCHAR(55) NOT NULL,
		SURNAME VARCHAR(55) NOT NULL
	);

CREATE UNIQUE INDEX SQL130119003746730 ON APPLICATIONUSER (USERID ASC);

ALTER TABLE APPLICATIONUSER ADD CONSTRAINT USERID_PK PRIMARY KEY (USERID);

